### ISSUE TITLE
I can Translate Japanese to English

### ISSUE THREAD

**Issue by MiYakuGaming** [unknownbrackets/tomatotrans#12]
I am a Translator of Japanese to English, I do not code and all I focus on is Translation.
If you want, I can contribute my Translations here as I am doing a Let's Translate series on Tomato Adventure, among others, on YouTube.

If you are interested in this and want me to Translate, I require credits to my YouTube Channel for more exposure :D
You can find my YouTube channel in my profile.

**Comment by unknownbrackets** [comment]
Certainly any translator deserves credit - it's the main part of the work.

If it's just making sure to link to a YouTube channel in documentation, release announcements, etc. that'd be no problem at all.  I'm no marketing genius, though.  Is that along the lines of what you were thinking?

I do want to note that I've been in contact with someone who has translated most of the script.  They have not translated all the battle event and menu text, though.  I also haven't seen the translated script yet - they've wanted to do some editing.

Would you be interested in helping with in-battle messages and things like item and Gimmick descriptions?  I think we'd want to also make sure everyone's translation styles are compatible too.

-[Unknown]

**Comment by MiYakuGaming** [comment]
Sure, I would enjoy a link to my Channel, release announcements, etc.

I can translate what you mentioned, and I will try to match the styles, but you are also free to edit it yourself too.
However, my translation on my Channel will likely be a bit different, I do not censor my work in any capacity, I am not sure if you do.

**Comment by unknownbrackets** [comment]
Thanks.  I'm still waiting to hear back from the person who said that had a completed script.  I don't know all their style preferences yet.

My personal position on styles is just that I want it to make sense.  If it's a joke, I want it to be funny.  That said, my Japanese is not at all strong and I don't mean to assert myself too much.  I'll likely just be editing.

To use examples from American English as reverse examples:

 * "a snail's pace" to mean slow, while possibly not a common phase everywhere, objectively makes sense as long as you know what a snail is.  So personally, I'd keep a phrase like that as-is.

 * "my ears are burning" to mean someone is talking about you, objectively makes no sense: "my ears are red" or "my ears are on fire" or "my ears are hurting" would all be confusing to someone who doesn't know about this idiom.  It's similar to sneezing when someone talks about you in Japanese culture.  So personally, I might consider changing something like this.

 * The most challenging are plays on words.  Personally, I dislike it when the context is changed entirely to preserve the joke (i.e. "I named my dog Elie because she's as big as a certain other animal" -> "Woah, did you see that bird?  It was huge, I'm gonna call that type of birds Phant.")  But jokes can be very challenging in general.

As far as censorship, that's probably not a big deal for this game either way.

-[Unknown]

**Comment by MiYakuGaming** [comment]
You can see my work in progress here:
https://github.com/MiYakuGaming/tomatotrans/blob/patch-1/ta_battle_jpn.txt

I see what you mean regarding edits, I do that a lot, but I do not soften the meaning at all.

**Comment by unknownbrackets** [comment]
Sorry for not responding, but this is great so far - thank you.  I should do more to give context on these - was following the original format of the files, but it's probably difficult with limited context.

-[Unknown]

**Comment by unknownbrackets** [comment]
Will reference some of what you worked on in editing.  Please see this branch for work in progress:
https://github.com/unknownbrackets/tomatotrans/tree/demille

-[Unknown]

**Comment by MiYakuGaming** [comment]
I have not given up on this, I was originally working on the translations until my YouTube Channel exploded in popularity, once I am done with a certain game I am coming to this.
