### ISSUE TITLE
Status Update?

### ISSUE THREAD

**Issue by megatyler30** [unknownbrackets/tomatotrans#13]
Years after originally looking for a TA translation, I searched again today and found this. Thanks for working on this! 

I am by no means here to rush you, as this is a fan project and all. But I would appreciate a status put on the main page. Just something indicating what percent of different categories (i.e. Menus, Dialogue, Graphics, etc.) are currently translated. This would be helpful for watching progress as I check every few months. Thanks again for doing this!

**Comment by unknownbrackets** [comment]
You can check romhacking.org for some updates, and also look at this branch:

https://github.com/unknownbrackets/tomatotrans/tree/demille

Basically, all the text is translated at this point (menus, dialog, battle) but some editing, proofreading, and testing is still happening.  There are a couple images that still need adjustments and we were discussing the "Oya Yubi" text (which is in romanji) and whether it made sense to translate that or not.  But I'm not sure if there might be more images, as we completely missed Alcatraz Hotel the first time through...

I'm not likely to put percentages to this, because most of the percentages would be high, but that doesn't mean it's a week away from release.  In software development generally, it takes 90% of the time to get 90% of the way done, and then another 90% of the time to finish.  Percentages are usually misleading.

-[Unknown]

**Comment by megatyler30** [comment]
I think percentages are more useful for people deciding if it's complete enough to decide to play it rather than a timeline to completetion. Based on what you've said, I will probably give it a try soon when I get some time. Thanks again!
