### ISSUE TITLE
Graphical issues when equipping gimmicks under rare circumstances

### ISSUE THREAD

**Issue by Kilicool64** [unknownbrackets/tomatotrans#20]
Though I never had issues with this in the past, I just ran into a fairly major graphical glitch. Parts of the menu remain glitched until you close it.
![Tomato Adventure  en-us 1 1 0 -0](https://user-images.githubusercontent.com/53983097/221619517-d320f3bf-444c-4ccb-aa64-9b31379375d2.png)

To reproduce this, here's my save file: [Tomato Adventure gimmick swap glitch save.zip](https://github.com/unknownbrackets/tomatotrans/files/10841728/Tomato.Adventure.gimmick.swap.glitch.save.zip)
Load the third save and try equipping Rellek with one of his two currently unequipped gimmicks.

It's impossible for this to be an emulator issue. I originally ran into it while playing the game natively on a modded 3DS. I only reproduced it in mGBA to make a screenshot.

I hope it's not too late for this to be fixed.

**Comment by unknownbrackets** [comment]
Interesting.  Thanks for the report and savedata - it's not too late.

Fixed in 3cd79bc74eedccd129e1e1607af2e59f76cbc5b6.

It seems the game ran out of OAM space (that's the metadata for what sprites are on screen), and tried to show some sort of debug message perhaps.  It seems like the code for the debug message is broken (not by this patch, even in the original game), and that's why so many things got messed up.

Rellek was the only one affected in this save because each of the digits (for attack, etc.) take up a "sprite" and so he had the most sprites of anyone.  The bug was the original game double-allocated all these sprites, so it ran out of space way faster than it should.

The fix just prevents the double allocation.  I haven't created a new build/release yet, but will plan to.

If you find any other issues definitely report them.

-[Unknown]
