### ISSUE TITLE
Issue rendering uppercase E

### ISSUE THREAD

**Issue by Kilicool64** [unknownbrackets/tomatotrans#21]
A lot of the time, the game fails to fully render this character, with its top left corner missing. Here's a screenshot from a video just before the first phase of the final battle:
![image](https://user-images.githubusercontent.com/53983097/226443082-088f323d-2846-42c7-a52f-4b30b17055b4.png)

**Comment by unknownbrackets** [comment]
Actually, the issue was with V.  Its width was wrong, but that's annoying to fix because it can cause wrapping issues.

Instead, I've shifted the V left in 3b57865.  This means the top left of the V will connect with E and T that come before it which affects these words mainly:
 * Letters connect: TV, TNTV, BELIEVE, EVERYBODY, HOWEVER, EVACUATE, LIVE, ACTIVATED
 * No connection: OVERWEIGHT, COVER, OVER, MOVES, MOVE, ADVANCE, BRAVO, HAVE, SAVE, LEAVE, LOVE, AVALANCHE

Not counting when a V is the first letter of a word, which should not really be negatively impacted.  It's not ideal for them to touch, but honestly "HAVE" looks better this way, so I think it's better on the balance.

-[Unknown]

**Comment by unknownbrackets** [comment]
Here's a screenshot of how the connected TV looks, for example.  I don't think it's terrible:

!["This dang TV" screenshot](https://user-images.githubusercontent.com/191233/227801625-10bcbc4b-856b-4cd7-9f93-9cb20c07bfd8.png)

I could also just make the V thinner, I guess.  Anyway, I'm going to close this but if you think it looks really bad, let me know in a reply.

-[Unknown]

**Comment by Kilicool64** [comment]
I guess this looks passable, though not ideal. Perhaps a thinner V would be preferable. Can't say for sure until I see it, though.

**Comment by unknownbrackets** [comment]
A thinner V would look like this.  Wouldn't cause problems with wrapping.

!["This dang TV" screenshot](https://user-images.githubusercontent.com/191233/227808185-0039d45c-726a-4ea4-acf1-17b21deb07c2.png)

-[Unknown]

**Comment by Kilicool64** [comment]
By itself, I think I prefer the thicker V, but it looks weird when it blends together with the letter preceding it. So I think the thinner one is slightly better. I can understand not wanting to test the whole game again just to make sure a properly adjusted thick V doesn't cause any issues.

**Comment by unknownbrackets** [comment]
Fair enough.  Looking at the text with capital Vs in it, many were shorter like "Very well", so I went ahead and checked the longer ones.  Here's a VPS with the wider V and correct width.

[Tomato Adventure [en-us 1.1.0-6-g5707c1a].zip](https://github.com/unknownbrackets/tomatotrans/files/11107425/Tomato.Adventure.en-us.1.1.0-6-g5707c1a.zip)

-[Unknown]

**Comment by Kilicool64** [comment]
My playthrough of the game is already done, so I probably won't be needing this for the foreseeable future, but thanks anyway.
